### ISSUE TITLE
Create database automatically

### ISSUE THREAD

**Issue by max-wittig** [deadlocker8/BudgetMaster#149]
Currently as of version 1.3.0 the user has to create the budgetmaster database. Could this database possibly created automatically, while the budgetmaster is running for the first time?

**Comment by deadlocker8** [comment]
This is no option because root mysql priviliges are requiered for database creation.
Why would you grant root priviliges to a programm like BudgetMaster?
This would be a security issue. 
Even software like wordpress needs a already created database and according credentials while installation.
