### ISSUE TITLE
Wrong redirection on month change in transaction list

### ISSUE THREAD

**Issue by Tobisaninfo** [deadlocker8/BudgetMaster#418]
Then running BudgetMaster in Tomcat and changing the month of the transaction view, the redirect is wrong. This happens in the date picker and step buttons.

Current Redirect: http://<host>:8080/BudgetMaster/**BudgetMaster**/transactions
Expected Redirect: http://<host>:8080/BudgetMaster/transactions

**Comment by deadlocker8** [comment]
use server.servlet.context-path=/<name_here> in application.properties for debug purposes
