### ISSUE TITLE
Unable to initiate installation process. 

### ISSUE THREAD

**Issue by HarryHeights** [deadlocker8/BudgetMaster#459]
I downloaded the app, and I tried to install it. The first time, it pointed out that my java runtime was outdated. I promptly updated it(java runtime). I tried to install the software and it wouldn't install.

#### Test Environment
Device; HP Pavilion dv7
OS; Windows 8.1

**Comment by deadlocker8** [comment]
Thanks for the feedback.
The app itself doesn't need to install. You simply run it. On the first run a default settings file will be created in your app data directory `%appdata%/Deadlocker/BudgetMaster`. You have to modify this file according to your needs. Further information could be found in the wiki section [https://github.com/deadlocker8/BudgetMaster/wiki/Installation](https://github.com/deadlocker8/BudgetMaster/wiki/Installation)

**Comment by deadlocker8** [comment]
Closed for now. Will re-open if you sitll have questions.
